create table Customers(
    CustomerID NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    FirstName VARCHAR2(50) NOT NULL,
    LastName VARCHAR2(50) NOT NULL,
    Email VARCHAR2(100) UNIQUE NOT NULL,
    PhoneNumber VARCHAR2(15),
    CreatedAt TIMESTAMP DEFAULT CURRENT_TIMESTAMP 
);

create table Accounts(
    AccountID number generated by default as identity primary key,
    CustomerID number not null,
    AccountType varchar2(20) check(AccountType In('Savings','Current')),
    Balance Number(15,2) default 0.00 check(balance >=0),
    Status varchar2(15) default 'Active' check(Status IN ('Active','Frozen','Closed')),
    constraint fk_customer foreign key (CustomerID) references Customers(CustomerID)
);

create table Transactions(
    TransactionID number generated by default as identity primary key,
    FromAccountID Number,
    ToAccountID Number,
    Amount Number(15,2) not null check(Amount >0),
    TransactionType varchar2(20) check(TransactionType IN('Deposit','Withdrawal','Transfer')),
    TransactionDate Timestamp Default CURRENT_TIMESTAMP,
    constraint fk_from_account foreign key (FromAccountID) references Accounts(AccountID),
    constraint fk_to_account foreign key (ToAccountID) references Accounts(AccountID)

);
